### ISSUE TITLE
Some Questoin

### ISSUE THREAD

**Issue by kimZLeung** [JoeBBChen/FE-Knowledge#2]
- 大概看了一下，理解了一个promise里面的链里面有这个promise的fulfilled函数，还有this指向下一个promise的resolve函数
- 然后再上一个promise里面调用reslove()的话会通过下一个promise的链去调用下一个promise的fullfilled函数。这样吗？
- 关于reslove.js第36行的块语句中对这个promise调用then方法的目的是什么，可能我看乱了自己。
- _Promise.js里面的第47行push的是不是应该是reject?

**Comment by JoeBBChen** [comment]
3、4点，自己再理解一下API先
